name: Build and Push Docker Images

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Login to registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/qjoly/talos.coffee.extension/app
          tags: |
              type=ref,event=tag
              type=raw,value=${{ github.head_ref || github.ref_name }}
              type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: coffee
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
      - name: Create Installer
        env:
          IMAGE_EXT: ghcr.io/qjoly/talos.coffee.extension/app
          TALOS_VERSION: v1.8.1
          ARCH: amd64
          PROFILE: installer
        run: |
          docker run --rm -t -v /dev:/dev --privileged -e GITHUB_TOKEN=${{ secrets.GHCR_PAT }} -v "$PWD/_out:/out" \
            "ghcr.io/siderolabs/imager:${TALOS_VERSION}" --arch "${ARCH}" \
            --system-extension-image ${IMAGE_EXT} "${PROFILE}"
          docker load -i ./_out/installer-${ARCH}.tar 
          docker tag ghcr.io/siderolabs/installer:${TALOS_VERSION} ghcr.io/qjoly/talos.coffee.extension/installer:${TALOS_VERSION}-${{ github.ref_name }}
          docker push ghcr.io/qjoly/talos.coffee.extension/installer:${TALOS_VERSION}-${{ github.ref_name }}
    
      - name: Create Installer
        # if: startsWith(github.event.ref, 'refs/tags/v')
        env:
          IMAGE_EXT: ghcr.io/qjoly/talos.coffee.extension/app
          TALOS_VERSION: v1.8.1
          ARCH: amd64
          PROFILE: iso
        run: |
          docker run --rm -t -v /dev:/dev --privileged -e GITHUB_TOKEN=${{ secrets.GHCR_PAT }} -v "$PWD/_out:/out" \
            "ghcr.io/siderolabs/imager:${TALOS_VERSION}" --arch "${ARCH}" \
            --system-extension-image ${IMAGE_EXT} "${PROFILE}"
            
      - name: Upload a Build Artifact
        # if: startsWith(github.event.ref, 'refs/tags/v')
        env:
          IMAGE_EXT: ghcr.io/qjoly/talos.coffee.extension/app
          TALOS_VERSION: v1.8.1
          ARCH: amd64
          PROFILE: iso
        uses: actions/upload-artifact@v4.4.3
        with:
          name: "${{ env.TALOS_VERSION }}-${{ env.ARCH }}.iso"
          path: "_out/metal-${{ env.ARCH }}.iso"
        
